Imports System.Runtime.InteropServices
Imports System.Runtime.InteropServices.ComTypes
Imports Laila.Shell.Interop
Imports Laila.Shell.Interop.DragDrop

Namespace Helpers
    Public Class DataObjectSpy
        Implements ComTypes.IDataObject

        Private _dataObject As ComTypes.IDataObject

        Public Sub New(dataObject As ComTypes.IDataObject)
            _dataObject = dataObject
        End Sub

        Public Sub GetData(ByRef format As ComTypes.FORMATETC, ByRef medium As ComTypes.STGMEDIUM) Implements ComTypes.IDataObject.GetData
            Select Case format.cfFormat
                Case ClipboardFormat.CF_HDROP
                    Debug.WriteLine("GetData CF_HDROP")
                Case Functions.RegisterClipboardFormat("DragImageBits")
                    Debug.WriteLine("GetData DragImageBits")
                Case Functions.RegisterClipboardFormat("ComputedImage")
                    Debug.WriteLine("GetData ComputedImage")
                Case Functions.RegisterClipboardFormat("IsComputingImage")
                    Debug.WriteLine("GetData IsComputingImage")
                Case Functions.RegisterClipboardFormat("DragSourceHelperFlags")
                    Debug.WriteLine("GetData DragSourceHelperFlags")
                Case Functions.RegisterClipboardFormat("DragContext")
                    Debug.WriteLine("GetData DragContext")
                Case Functions.RegisterClipboardFormat("DragWindow")
                    Debug.WriteLine("GetData DragWindow")
                Case Functions.RegisterClipboardFormat("DisableDragText")
                    Debug.WriteLine("GetData DisableDragText")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("GetData DropDescription")
                Case Functions.RegisterClipboardFormat("IsShowingLayered")
                    Debug.WriteLine("GetData IsShowingLayered")
                Case Functions.RegisterClipboardFormat("IsShowingText")
                    Debug.WriteLine("GetData IsShowingText")
                Case Functions.RegisterClipboardFormat("UsingDefaultDragImage")
                    Debug.WriteLine("GetData UsingDefaultDragImage")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptorW")
                    Debug.WriteLine("GetData FileGroupDescriptorW")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptor")
                    Debug.WriteLine("GetData FileGroupDescriptor")
                Case Functions.RegisterClipboardFormat("FileContents")
                    Debug.WriteLine("GetData FileContents")
                Case Functions.RegisterClipboardFormat("Shell IDList Array")
                    Debug.WriteLine("GetData Shell IDList Array")
                Case Functions.RegisterClipboardFormat("Shell Object Offsets")
                    Debug.WriteLine("GetData Shell Object Offsets")
                Case Functions.RegisterClipboardFormat("Net Resource")
                    Debug.WriteLine("GetData Net Resource")
                Case Functions.RegisterClipboardFormat("FileName")
                    Debug.WriteLine("GetData FileName")
                Case Functions.RegisterClipboardFormat("FileNameW")
                    Debug.WriteLine("GetData FileNameW")
                Case Functions.RegisterClipboardFormat("PrinterFriendlyName")
                    Debug.WriteLine("GetData PrinterFriendlyName")
                Case Functions.RegisterClipboardFormat("FileNameMap")
                    Debug.WriteLine("GetData FileNameMap")
                Case Functions.RegisterClipboardFormat("FileNameMapW")
                    Debug.WriteLine("GetData FileNameMapW")
                Case Functions.RegisterClipboardFormat("UniformResourceLocator")
                    Debug.WriteLine("GetData UniformResourceLocator")
                Case Functions.RegisterClipboardFormat("UniformResourceLocatorW")
                    Debug.WriteLine("GetData UniformResourceLocatorW")
                Case Functions.RegisterClipboardFormat("Preferred DropEffect")
                    Debug.WriteLine("GetData Preferred DropEffect")
                Case Functions.RegisterClipboardFormat("Performed DropEffect")
                    Debug.WriteLine("GetData Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Paste Succeeded")
                    Debug.WriteLine("GetData Paste Succeeded")
                Case Functions.RegisterClipboardFormat("InShellDragLoop")
                    Debug.WriteLine("GetData InShellDragLoop")
                Case Functions.RegisterClipboardFormat("MountedVolume")
                    Debug.WriteLine("GetData MountedVolume")
                Case Functions.RegisterClipboardFormat("PersistedDataObject")
                    Debug.WriteLine("GetData PersistedDataObject")
                Case Functions.RegisterClipboardFormat("TargetCLSID")
                    Debug.WriteLine("GetData TargetCLSID")
                Case Functions.RegisterClipboardFormat("Logical Performed DropEffect")
                    Debug.WriteLine("GetData Logical Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Autoplay Enumerated IDList Array")
                    Debug.WriteLine("GetData Autoplay Enumerated IDList Array")
                Case Functions.RegisterClipboardFormat("UntrustedDragDrop")
                    Debug.WriteLine("GetData UntrustedDragDrop")
                Case Functions.RegisterClipboardFormat("File Attributes Array")
                    Debug.WriteLine("GetData File Attributes Array")
                Case Functions.RegisterClipboardFormat("InvokeCommand DropParam")
                    Debug.WriteLine("GetData InvokeCommand DropParam")
                Case Functions.RegisterClipboardFormat("DropHandlerCLSID")
                    Debug.WriteLine("GetData DropHandlerCLSID")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("GetData DropDescription")
                Case Else
                    Debug.WriteLine("GetData " & format.cfFormat)
            End Select
            Debug.WriteLine("GetData " & format.tymed.ToString() & "," & format.lindex)

            _dataObject.GetData(format, medium)
        End Sub

        Public Sub GetDataHere(ByRef format As ComTypes.FORMATETC, ByRef medium As ComTypes.STGMEDIUM) Implements ComTypes.IDataObject.GetDataHere
            Debug.WriteLine("GetDataHere")

            _dataObject.GetDataHere(format, medium)
        End Sub

        Public Function QueryGetData(ByRef format As ComTypes.FORMATETC) As Integer Implements ComTypes.IDataObject.QueryGetData
            Select Case format.cfFormat
                Case ClipboardFormat.CF_HDROP
                    Debug.WriteLine("QueryGetData CF_HDROP")
                Case Functions.RegisterClipboardFormat("DragImageBits")
                    Debug.WriteLine("QueryGetData DragImageBits")
                Case Functions.RegisterClipboardFormat("ComputedImage")
                    Debug.WriteLine("QueryGetData ComputedImage")
                Case Functions.RegisterClipboardFormat("IsComputingImage")
                    Debug.WriteLine("QueryGetData IsComputingImage")
                Case Functions.RegisterClipboardFormat("DragSourceHelperFlags")
                    Debug.WriteLine("QueryGetData DragSourceHelperFlags")
                Case Functions.RegisterClipboardFormat("DragContext")
                    Debug.WriteLine("QueryGetData DragContext")
                Case Functions.RegisterClipboardFormat("DragWindow")
                    Debug.WriteLine("QueryGetData DragWindow")
                Case Functions.RegisterClipboardFormat("DisableDragText")
                    Debug.WriteLine("QueryGetData DisableDragText")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("QueryGetData DropDescription")
                Case Functions.RegisterClipboardFormat("IsShowingLayered")
                    Debug.WriteLine("QueryGetData IsShowingLayered")
                Case Functions.RegisterClipboardFormat("IsShowingText")
                    Debug.WriteLine("QueryGetData IsShowingText")
                Case Functions.RegisterClipboardFormat("UsingDefaultDragImage")
                    Debug.WriteLine("QueryGetData UsingDefaultDragImage")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptorW")
                    Debug.WriteLine("QueryGetData FileGroupDescriptorW")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptor")
                    Debug.WriteLine("QueryGetData FileGroupDescriptor")
                Case Functions.RegisterClipboardFormat("FileContents")
                    Debug.WriteLine("QueryGetData FileContents")
                Case Functions.RegisterClipboardFormat("Shell IDList Array")
                    Debug.WriteLine("QueryGetData Shell IDList Array")
                Case Functions.RegisterClipboardFormat("Shell Object Offsets")
                    Debug.WriteLine("QueryGetData Shell Object Offsets")
                Case Functions.RegisterClipboardFormat("Net Resource")
                    Debug.WriteLine("QueryGetData Net Resource")
                Case Functions.RegisterClipboardFormat("FileName")
                    Debug.WriteLine("QueryGetData FileName")
                Case Functions.RegisterClipboardFormat("FileNameW")
                    Debug.WriteLine("QueryGetData FileNameW")
                Case Functions.RegisterClipboardFormat("PrinterFriendlyName")
                    Debug.WriteLine("QueryGetData PrinterFriendlyName")
                Case Functions.RegisterClipboardFormat("FileNameMap")
                    Debug.WriteLine("QueryGetData FileNameMap")
                Case Functions.RegisterClipboardFormat("FileNameMapW")
                    Debug.WriteLine("QueryGetData FileNameMapW")
                Case Functions.RegisterClipboardFormat("UniformResourceLocator")
                    Debug.WriteLine("QueryGetData UniformResourceLocator")
                Case Functions.RegisterClipboardFormat("UniformResourceLocatorW")
                    Debug.WriteLine("QueryGetData UniformResourceLocatorW")
                Case Functions.RegisterClipboardFormat("Preferred DropEffect")
                    Debug.WriteLine("QueryGetData Preferred DropEffect")
                Case Functions.RegisterClipboardFormat("Performed DropEffect")
                    Debug.WriteLine("QueryGetData Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Paste Succeeded")
                    Debug.WriteLine("QueryGetData Paste Succeeded")
                Case Functions.RegisterClipboardFormat("InShellDragLoop")
                    Debug.WriteLine("QueryGetData InShellDragLoop")
                Case Functions.RegisterClipboardFormat("MountedVolume")
                    Debug.WriteLine("QueryGetData MountedVolume")
                Case Functions.RegisterClipboardFormat("PersistedDataObject")
                    Debug.WriteLine("QueryGetData PersistedDataObject")
                Case Functions.RegisterClipboardFormat("TargetCLSID")
                    Debug.WriteLine("QueryGetData TargetCLSID")
                Case Functions.RegisterClipboardFormat("Logical Performed DropEffect")
                    Debug.WriteLine("QueryGetData Logical Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Autoplay Enumerated IDList Array")
                    Debug.WriteLine("QueryGetData Autoplay Enumerated IDList Array")
                Case Functions.RegisterClipboardFormat("UntrustedDragDrop")
                    Debug.WriteLine("QueryGetData UntrustedDragDrop")
                Case Functions.RegisterClipboardFormat("File Attributes Array")
                    Debug.WriteLine("QueryGetData File Attributes Array")
                Case Functions.RegisterClipboardFormat("InvokeCommand DropParam")
                    Debug.WriteLine("QueryGetData InvokeCommand DropParam")
                Case Functions.RegisterClipboardFormat("DropHandlerCLSID")
                    Debug.WriteLine("QueryGetData DropHandlerCLSID")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("QueryGetData DropDescription")
                Case Else
                    Debug.WriteLine("QueryGetData " & format.cfFormat)
            End Select

            Debug.WriteLine("QueryGetData " & format.tymed.ToString() & "," & format.lindex)

            Return _dataObject.QueryGetData(format)
        End Function
        Public Function GetCanonicalFormatEtc(ByRef formatIn As ComTypes.FORMATETC, ByRef formatOut As ComTypes.FORMATETC) As Integer Implements ComTypes.IDataObject.GetCanonicalFormatEtc
            Debug.WriteLine("GetCanonicalFormatEtc")
            Return _dataObject.GetCanonicalFormatEtc(formatIn, formatOut)
        End Function

        Public Sub SetData(ByRef format As ComTypes.FORMATETC, ByRef medium As ComTypes.STGMEDIUM, ByVal release As Boolean) Implements ComTypes.IDataObject.SetData
            Select Case format.cfFormat
                Case ClipboardFormat.CF_HDROP
                    Debug.WriteLine("SetData CF_HDROP")
                Case Functions.RegisterClipboardFormat("DragImageBits")
                    Debug.WriteLine("SetData DragImageBits")
                Case Functions.RegisterClipboardFormat("ComputedImage")
                    Debug.WriteLine("SetData ComputedImage")
                Case Functions.RegisterClipboardFormat("IsComputingImage")
                    Debug.WriteLine("SetData IsComputingImage")
                Case Functions.RegisterClipboardFormat("DragSourceHelperFlags")
                    Debug.WriteLine("SetData DragSourceHelperFlags")
                Case Functions.RegisterClipboardFormat("DragContext")
                    Debug.WriteLine("SetData DragContext")
                Case Functions.RegisterClipboardFormat("DragWindow")
                    Debug.WriteLine("SetData DragWindow")
                Case Functions.RegisterClipboardFormat("DisableDragText")
                    Debug.WriteLine("SetData DisableDragText")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("SetData DropDescription")
                Case Functions.RegisterClipboardFormat("IsShowingLayered")
                    Debug.WriteLine("SetData IsShowingLayered")
                Case Functions.RegisterClipboardFormat("IsShowingText")
                    Debug.WriteLine("SetData IsShowingText")
                Case Functions.RegisterClipboardFormat("UsingDefaultDragImage")
                    Debug.WriteLine("SetData UsingDefaultDragImage")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptorW")
                    Debug.WriteLine("SetData FileGroupDescriptorW")
                Case Functions.RegisterClipboardFormat("FileGroupDescriptor")
                    Debug.WriteLine("SetData FileGroupDescriptor")
                Case Functions.RegisterClipboardFormat("FileContents")
                    Debug.WriteLine("SetData FileContents")
                Case Functions.RegisterClipboardFormat("Shell IDList Array")
                    Debug.WriteLine("SetData Shell IDList Array")
                Case Functions.RegisterClipboardFormat("Shell Object Offsets")
                    Debug.WriteLine("SetData Shell Object Offsets")
                Case Functions.RegisterClipboardFormat("Net Resource")
                    Debug.WriteLine("SetData Net Resource")
                Case Functions.RegisterClipboardFormat("FileName")
                    Debug.WriteLine("SetData FileName")
                Case Functions.RegisterClipboardFormat("FileNameW")
                    Debug.WriteLine("SetData FileNameW")
                Case Functions.RegisterClipboardFormat("PrinterFriendlyName")
                    Debug.WriteLine("SetData PrinterFriendlyName")
                Case Functions.RegisterClipboardFormat("FileNameMap")
                    Debug.WriteLine("SetData FileNameMap")
                Case Functions.RegisterClipboardFormat("FileNameMapW")
                    Debug.WriteLine("SetData FileNameMapW")
                Case Functions.RegisterClipboardFormat("UniformResourceLocator")
                    Debug.WriteLine("SetData UniformResourceLocator")
                Case Functions.RegisterClipboardFormat("UniformResourceLocatorW")
                    Debug.WriteLine("SetData UniformResourceLocatorW")
                Case Functions.RegisterClipboardFormat("Preferred DropEffect")
                    Debug.WriteLine("SetData Preferred DropEffect")
                Case Functions.RegisterClipboardFormat("Performed DropEffect")
                    Debug.WriteLine("SetData Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Paste Succeeded")
                    Debug.WriteLine("SetData Paste Succeeded")
                Case Functions.RegisterClipboardFormat("InShellDragLoop")
                    Debug.WriteLine("SetData InShellDragLoop")
                Case Functions.RegisterClipboardFormat("MountedVolume")
                    Debug.WriteLine("SetData MountedVolume")
                Case Functions.RegisterClipboardFormat("PersistedDataObject")
                    Debug.WriteLine("SetData PersistedDataObject")
                Case Functions.RegisterClipboardFormat("TargetCLSID")
                    Debug.WriteLine("SetData TargetCLSID")
                Case Functions.RegisterClipboardFormat("Logical Performed DropEffect")
                    Debug.WriteLine("SetData Logical Performed DropEffect")
                Case Functions.RegisterClipboardFormat("Autoplay Enumerated IDList Array")
                    Debug.WriteLine("SetData Autoplay Enumerated IDList Array")
                Case Functions.RegisterClipboardFormat("UntrustedDragDrop")
                    Debug.WriteLine("SetData UntrustedDragDrop")
                Case Functions.RegisterClipboardFormat("File Attributes Array")
                    Debug.WriteLine("SetData File Attributes Array")
                Case Functions.RegisterClipboardFormat("InvokeCommand DropParam")
                    Debug.WriteLine("SetData InvokeCommand DropParam")
                Case Functions.RegisterClipboardFormat("DropHandlerCLSID")
                    Debug.WriteLine("SetData DropHandlerCLSID")
                Case Functions.RegisterClipboardFormat("DropDescription")
                    Debug.WriteLine("SetData DropDescription")
                Case Else
                    Debug.WriteLine("SetData " & format.cfFormat)
            End Select

            _dataObject.SetData(format, medium, release)
        End Sub

        Public Function EnumFormatEtc(ByVal direction As ComTypes.DATADIR) As ComTypes.IEnumFORMATETC Implements ComTypes.IDataObject.EnumFormatEtc
            Debug.WriteLine("EnumFormatEtc")
            Return _dataObject.EnumFormatEtc(direction)
        End Function

        Public Function DAdvise(ByRef pFormatetc As ComTypes.FORMATETC, advf As ADVF, adviseSink As ComTypes.IAdviseSink, ByRef connection As Integer) As Integer Implements ComTypes.IDataObject.DAdvise
            Debug.WriteLine("DAdvise")
            Return &H80004001 ' E_NOTIMPL
        End Function

        Public Sub DUnadvise(ByVal connection As Integer) Implements ComTypes.IDataObject.DUnadvise
            Debug.WriteLine("DUnadvise")
            ' Return &H80004001 ' E_NOTIMPL
        End Sub

        Public Function EnumDAdvise(ByRef enumAdvise As ComTypes.IEnumSTATDATA) As Integer Implements ComTypes.IDataObject.EnumDAdvise
            Debug.WriteLine("EnumDAdvise")
            Return &H80004001 ' E_NOTIMPL
        End Function
    End Class
End Namespace