Namespace Interop.Properties
    Public Enum PROPDESC_TYPE_FLAGS
        PDTF_DEFAULT = 0
        PDTF_MULTIPLEVALUES = &H1
        PDTF_ISINNATE = &H2
        PDTF_ISGROUP = &H4
        PDTF_CANGROUPBY = &H8
        PDTF_CANSTACKBY = &H10
        PDTF_ISTREEPROPERTY = &H20
        PDTF_INCLUDEINFULLTEXTQUERY = &H40
        PDTF_ISVIEWABLE = &H80
        PDTF_ISQUERYABLE = &H100
        PDTF_CANBEPURGED = &H200
        PDTF_SEARCHRAWVALUE = &H400
        PDTF_DONTCOERCEEMPTYSTRINGS = &H800
        PDTF_ALWAYSINSUPPLEMENTALSTORE = &H1000
        PDTF_ISSYSTEMPROPERTY = &H80000000
        PDTF_MASK_ALL = &H80001FFF
    End Enum
End Namespace

