Namespace Interop.ContextMenu
    Public Enum DFM
        DFM_MERGECONTEXTMENU = 1
        DFM_INVOKECOMMAND = 2
        DFM_GETHELPTEXT = 5
        DFM_WM_MEASUREITEM = 6
        DFM_WM_DRAWITEM = 7
        DFM_WM_INITMENUPOPUP = 8
        DFM_VALIDATECMD = 9
        DFM_MERGECONTEXTMENU_TOP = 10
        DFM_MERGECONTEXTMENU_BOTTOM = 11
        DFM_MODIFYQCMFLAGS = 12
        DFM_INVOKECOMMANDEX = 13
        DFM_GETHELPTEXTW = 14
        DFM_GETVERBW = 15
    End Enum
End Namespace
