Public Enum DropImageType
    DROPIMAGE_NONE = 0
    DROPIMAGE_COPY = 1
    DROPIMAGE_MOVE = 2
    DROPIMAGE_LINK = 3
    DROPIMAGE_LABEL = 4
    DROPIMAGE_WARNING = 5
    DROPIMAGE_NOIMAGE = 6
End Enum