<Flags>
Public Enum DROPEFFECT
    DROPEFFECT_NONE = 0
    DROPEFFECT_COPY = 1
    DROPEFFECT_MOVE = 2
    DROPEFFECT_LINK = 4
    DROPEFFECT_SCROLL = &H80000000
    DROPEFFECT_ALL = (DROPEFFECT_COPY Or DROPEFFECT_MOVE Or DROPEFFECT_LINK Or DROPEFFECT_SCROLL)
End Enum