Public Enum PROPDESC_VIEW_FLAGS
    PDVF_DEFAULT = 0
    PDVF_CENTERALIGN = &H1
    PDVF_RIGHTALIGN = &H2
    PDVF_BEGINNEWGROUP = &H4
    PDVF_FILLAREA = &H8
    PDVF_SORTDESCENDING = &H10
    PDVF_SHOWONLYIFPRESENT = &H20
    PDVF_SHOWBYDEFAULT = &H40
    PDVF_SHOWINPRIMARYLIST = &H80
    PDVF_SHOWINSECONDARYLIST = &H100
    PDVF_HIDELABEL = &H200
    PDVF_HIDDEN = &H800
    PDVF_CANWRAP = &H1000
    PDVF_MASK_ALL = &H1BFF
End Enum
