name: Build and Publish Laila.Shell SampleApp2

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore Laila.Shell.sln

      - name: Extract Version from Tag
        id: extract_version
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}"
          $isPrerelease = $version -match "alpha"
          Write-Output "version=$version" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Output "prerelease=$isPrerelease" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Explicitly build WinRT dependency
        run: |
          msbuild Laila.Shell.WinRT/Laila.Shell.WinRT.csproj /p:Configuration=Release /p:Platform="x64" /m

      - name: Build Solution
        run: |
          msbuild Laila.Shell.sln /p:Configuration=Release /p:Platform="x64" /m

      - name: Pack Laila.Shell NuGet
        run: |
          msbuild Laila.Shell/Laila.Shell.vbproj /t:pack /p:Configuration=Release /p:Platform="x64"

      - name: Package SampleApp2
        run: |
          $outputDir = "./Laila.Shell.SampleApp/bin/x64/Release/net6.0-windows7.0"
          $zipFile = "Laila.Shell.SampleApp2-${{ steps.extract_version.outputs.version }}.zip"
          Compress-Archive -Path "$outputDir/*" -DestinationPath "$zipFile"

      - name: Upload SampleApp2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Laila.Shell.SampleApp2-${{ steps.extract_version.outputs.version }}
          path: ./Laila.Shell.SampleApp/bin/x64/Release/net6.0-windows7.0/*

      - name: Upload Laila.Shell NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Laila.Shell-nuget-${{ steps.extract_version.outputs.version }}
          path: ./Laila.Shell/bin/x64/Release/net6.0-windows7.0/*.nupkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: ${{ steps.extract_version.outputs.prerelease }}
          files: |
            Laila.Shell.SampleApp2-${{ steps.extract_version.outputs.version }}.zip
            ./Laila.Shell/bin/x64/Release/net6.0-windows7.0/*.nupkg